version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    environment:
      PLUGIN_PAGER_DUTY_ACCESS_TOKEN: $PLUGIN_PAGER_DUTY_ACCESS_TOKEN
    ports:
      - "3001:8080"
    restart: unless-stopped
    depends_on:
      - mysql

  grafana:
    build:
      context: ./.docker/grafana
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "3002:3000"
    environment:
      GF_DATABASE_URL: mysql://root:root@mysql:3306/grafana
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin123
      GF_SECURITY_DISABLE_GRAVATAR: 'true'
      GF_PATHS_PROVISIONING: /var/lib/grafana/provisioning
      DATASOURCE_HOST: mysql
      DATASOURCE_PORT: 3306
      DATASOURCE_DATABASE: dpe_insights
      DATASOURCE_USER: root
      DATASOURCE_PASSWORD: root
    restart: on-failure
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./.docker/grafana/var/lib/grafana/provisioning:/var/lib/grafana/provisioning

  mysql:
    image: mariadb:10
    ports:
      - '3307:3306'
    volumes:
      - mysql-storage:/var/lib/mysql
      - ./.docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dpe_insights

volumes:
  grafana-storage:
  mysql-storage:
