{
 "title": "Engineering Performance",
 "description": "Pull request Insights",
 "tags": [
  "git",
  "pagerduty"
 ],
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "team_slug",
    "label": "Team",
    "query": "SELECT slug FROM extracted_teams a \nUNION\nSELECT team_slug FROM map_pagerduty_service_name_team_slug"
   },
   {
    "name": "interval",
    "label": "Interval for average calculation",
    "query": "1d,1w,2w,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Lead Time",
   "type": "graph",
   "description": "The time between first commit and pull request merged.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "yaxes": [
    { "format": "h", "label": "Duration" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(pr_closed_at,$interval),\n  team_slug AS metric,\n  sum(TIMESTAMPDIFF(HOUR, first_commit_at, pr_merged_at))/count(pr_id) as lead_time_for_change\nFROM transformed_pull_request_data\nWHERE\n  $__timeFilter(pr_closed_at) AND\n  team_slug IN($team_slug)\nGROUP BY 1,2\nORDER BY $__timeGroup(pr_closed_at, $interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(pr_closed_at, $interval),\n  sum(TIMESTAMPDIFF(HOUR, first_commit_at, pr_merged_at))/count(pr_id) as lead_time_for_change,\n  \"global\" as metric\nFROM transformed_pull_request_data\nWHERE\n  $__timeFilter(pr_closed_at)\nGROUP BY 1\nORDER BY $__timeGroup(pr_closed_at, $interval)"
    }
   ]
  },
  {
   "title": "Deployment Frequency (avg per team)",
   "type": "graph",
   "description": "Releases",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  $__timeGroupAlias(er.created_at,$interval),\n  et.slug AS metric,\n  count(er.id) as \"Releases\"\nFROM extracted_releases as er\n\nLEFT JOIN extracted_team_repositories as etr\nON etr.github_repository_id = er.repository_id\n\nLEFT JOIN extracted_teams et\nON etr.github_team_id = et.id\n\nWHERE\n  $__timeFilter(er.created_at) AND\n  (et.slug IN($team_slug) OR et.slug = 'global') AND\n  et.slug NOT REGEXP '(^sendinblue|-review)$'\nGROUP BY 1,2\nORDER BY $__timeGroup(er.created_at, $interval)"
    },
    {
     "rawSql": "SELECT \n  $__timeGroupAlias(er.created_at,$interval),\n  \"global\" as metric,\n  COUNT(er.id)/(SELECT count(*) FROM extracted_teams WHERE slug NOT REGEXP '(^sendinblue|-review)$') as \"Releases\"\nFROM extracted_releases as er\n\nLEFT JOIN extracted_team_repositories as etr\nON etr.github_repository_id = er.repository_id\n\nLEFT JOIN extracted_teams et\nON etr.github_team_id = et.id\n\n\nWHERE\n  $__timeFilter(er.created_at) AND\n  et.slug NOT REGEXP '(^sendinblue|-review)$'\n\nGROUP BY 1\nORDER BY $__timeGroup(er.created_at, $interval)"
    }
   ]
  },
  {
   "title": "MTTR (High Urgency)",
   "type": "graph",
   "description": "Mean Time to Restore - Per team/serves time between the beginning of an incident and the time it is resolved.\n\n(Less is better)",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$interval),\n  IFNULL(mpsnts.team_slug, epi.service_name) AS team_slug,\n  avg(duration) AS \"duration\"\nFROM extracted_pagerduty_incidents as epi\nLEFT JOIN map_pagerduty_service_name_team_slug mpsnts ON epi.service_name = mpsnts.service_name\nWHERE\n  $__timeFilter(created_at) AND\n  urgency = 'high' AND\n  team_slug IN($team_slug)\nGROUP BY 1,2\nORDER BY $__timeGroup(created_at, $interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$interval),\n  avg(duration) AS \"global\"\nFROM extracted_pagerduty_incidents as epi\nLEFT JOIN map_pagerduty_service_name_team_slug mpsnts ON epi.service_name = mpsnts.service_name\nWHERE\n  $__timeFilter(created_at) AND\n  urgency = 'high'\nGROUP BY 1\nORDER BY $__timeGroup(created_at, $interval)"
    }
   ]
  },
  {
   "title": "Change Fail Percentage (Hotfixes+Reverts)",
   "type": "graph",
   "description": "\n\n(Less is better)",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(pr_created_at,$interval),\n  team_slug,\n  # SUM(IF(branch_name LIKE 'hotfix%', 1, 0)) AS hotfix,\n  # SUM(IF(branch_name LIKE 'revert%', 1, 0)) AS revert,\n  # COUNT(*) AS total,\n  (SUM(IF(branch_name LIKE 'hotfix%', 1, 0)) + SUM(IF(branch_name LIKE 'revert%', 1, 0))) / COUNT(*) AS change_fail_ratio\nFROM transformed_pull_request_data\nWHERE\n  $__timeFilter(pr_created_at) and\n  team_slug IN($team_slug)\nGROUP BY 1,2\nORDER BY $__timeGroup(pr_created_at, $interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(pr_created_at,$interval),\n  \"global\",\n  # SUM(IF(branch_name LIKE 'hotfix%', 1, 0)) AS hotfix,\n  # SUM(IF(branch_name LIKE 'revert%', 1, 0)) AS revert,\n  # COUNT(*) AS total,\n  (SUM(IF(branch_name LIKE 'hotfix%', 1, 0)) + SUM(IF(branch_name LIKE 'revert%', 1, 0))) / COUNT(*) AS change_fail_ratio\nFROM transformed_pull_request_data\nWHERE\n  $__timeFilter(pr_created_at)\nGROUP BY 1,2\nORDER BY $__timeGroup(pr_created_at, $interval)"
    }
   ]
  }
 ]
}